sqlite:
  db_path: "./data/book_manager.db"  # SQLite 数据库文件路径

redis:
  addr: "100.126.1.89:6379"    # 例如 "192.168.1.100:6379"
  password: ""                      # Redis 密码（无密码则留空）
  db: 0                             # Redis 数据库编号

server:
  port: 8888
